name: Build image and deploy to ECS
on:
    push:
        branches:
            - main
    workflow_dispatch:

env:    
    NODE_IMAGE_NAME: washer
  
jobs:
    build-image-node: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3.4.03
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: added details to image
              id: meta
              uses: docker/metadata-action@v5.7.0
              with:
                images: ${{ vars.DOCKER_USERNAME }}/${{ env.NODE_IMAGE_NAME }}
                tags:
                    latest
                    v1.0.${{ github.run_number }}                     
            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v6.15.0
              with:
                context: ./jokes-app-mern/API-jokes
                file: ./jokes-app-mern/API-jokes/Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}